import "../lib/component/hand-drawn-button.js"
import "../lib/component/hand-drawn-icon.js"
import "../lib/component/hand-drawn-pad.js"
import "../lib/component/hand-drawn-checkbox.js"
import "../lib/component/hand-drawn-radio.js"
